version: '3'

services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    ports:
      - '3050:80'
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    # Specify environment variables
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DBNAME=postgres
      - PG_PASS=postgres_password
